// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// naive_tau_kendall_cpp
double naive_tau_kendall_cpp(NumericVector x, NumericVector y);
RcppExport SEXP _Kendall_naive_tau_kendall_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(naive_tau_kendall_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// NDtau_kendall_cpp
double NDtau_kendall_cpp(NumericVector X, NumericVector Y);
RcppExport SEXP _Kendall_NDtau_kendall_cpp(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(NDtau_kendall_cpp(X, Y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Kendall_naive_tau_kendall_cpp", (DL_FUNC) &_Kendall_naive_tau_kendall_cpp, 2},
    {"_Kendall_NDtau_kendall_cpp", (DL_FUNC) &_Kendall_NDtau_kendall_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_Kendall(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
