
```{r}
devtools::install_github("GuillaumeAsty/Kendall_Tau")

library(ggplot2)
library(Rcpp)

library(Kendall)
```

## Génération des données synthétiques

```{r}
# Fonction pour générer des données synthétiques

generate_correlated_data <- function(n = 100) {

  # Génère un tau de Kendall aléatoire entre -1 et 1
  tau <- runif(1, -1, 1)
  
  # Approximation de la corrélation de Pearson à partir du tau de Kendall
  rho <- sin(tau * pi / 2)
  
  # Génére deux variables normales standard indépendantes
  X <- rnorm(n)
  Z <- rnorm(n)
  
  # Construit Y avec la corrélation rho
  Y <- rho * X + sqrt(1 - rho^2) * Z
  
  return(list(X = X, Y = Y, tau = tau, rho = rho))
}

data <- generate_correlated_data(100)
x <- data$X
y <- data$Y

```

## Test des fonctions

```{r}
# Implémentation en R avec une complexité en N^2
tau_R_naif <- naive_tau_kendall_R(x, y)

# Implémentation en R avec une complexité en NlogN
tau_R_ND <- NDtau_kendall_R(x, y)

# Implémentation en Rcpp avec une complexité en N^2
tau_cpp_naif <- naive_tau_kendall_cpp(x, y)

# Implémentation en Rcpp avec une complexité en NlogN
tau_cpp_ND <- NDtau_kendall_cpp(x, y)
```
