# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

naive_tau_kendall_cpp <- function(x, y) {
    .Call(`_Kendall_naive_tau_kendall_cpp`, x, y)
}

NDtau_kendall_cpp <- function(X, Y) {
    .Call(`_Kendall_NDtau_kendall_cpp`, X, Y)
}

